# Generated by Django 3.1.7 on 2021-04-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("G", "Natural Gass"),
                            ("E", "Electricity"),
                            ("W", "Water"),
                        ],
                        max_length=1,
                    ),
                ),
                ("unit", models.CharField(max_length=25)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consumptions.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consumption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading_date_time", models.DateTimeField(auto_now_add=True)),
                ("consumption", models.FloatField()),
                (
                    "meter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consumptions.meter",
                    ),
                ),
            ],
        ),
    ]
