# Generated by Django 3.1.7 on 2021-04-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meter",
            name="fuel",
            field=models.CharField(max_length=25),
        ),
    ]
