# Generated by Django 3.1.7 on 2021-04-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0002_auto_20210404_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='meter_id',
            new_name='meter',
        ),
    ]
